# Generated by Django 5.2.8 on 2025-11-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
